<a href="https://colab.research.google.com/github/stevenkhwun/Brooks4e/blob/main/DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
# Specify values for each column
df1 = pd.DataFrame(
    {"a" : [4, 5, 6],
     "b" : [7, 8, 9],
     "c" : [10, 11, 12]},
    index = [1, 2, 3]
)
df1

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [7]:
# Specify values for each row
df2 = pd.DataFrame(
    [[4, 7, 10],
     [5, 8, 11],
     [6, 9, 12]],
    index = [1, 2, 3],
    columns = ['a', 'b', 'c']
)
df2

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [11]:
# Create DataFrame with a MultiIndex
df3 = pd.DataFrame(
    {"a" : [4, 5, 6],
     "b" : [7, 8, 9],
     "c" : [10, 11, 12]},
    index = pd.MultiIndex.from_tuples(
        [('d', 1), ('d', 2),
         ('e', 2)], names = ['n', 'v']
    )
)
df3

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12